name: apig-check

on:
  pull_request:
    branches:
      - main
      - master
      - feature/init_openapi
    paths:
      - 'apig/**'
      - '**/*.go'
      - '**/*.java'
      - '**/*.py'
      - '.github/workflows/apig-check.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    uses: 2511689622/gen-openapi/.github/workflows/reusable-apig-check.yml@main
    with:
      gen_openapi_ref: main
    secrets:
      gen_openapi_token: ${{ secrets.GEN_OPENAPI_TOKEN }}
