package pr

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	"gen-openapi/internal/diff"
	"gen-openapi/internal/output"
	"gen-openapi/pkg/contract"
)

type call struct {
	Dir   string
	Name  string
	Args  []string
	Stdin string
}

type fakeRunner struct {
	outputs map[string]string
	errors  map[string]error
	calls   []call
}

func (f *fakeRunner) Run(ctx context.Context, dir, name string, args []string, stdin string) (string, error) {
	c := call{Dir: dir, Name: name, Args: append([]string(nil), args...), Stdin: stdin}
	f.calls = append(f.calls, c)
	key := name + " " + strings.Join(args, " ")
	if err := f.errors[key]; err != nil {
		return f.outputs[key], err
	}
	return f.outputs[key], nil
}

func TestCheckDirtyStatus(t *testing.T) {
	cases := []struct {
		name    string
		status  string
		wantErr bool
	}{
		{name: "clean", status: "", wantErr: false},
		{name: "untracked detected allowed", status: "?? api/api-contract.detected.yaml\n", wantErr: false},
		{name: "modified tracked rejected", status: " M api/api-contract.yaml\n", wantErr: true},
		{name: "staged rejected", status: "M  api/api-contract.yaml\n", wantErr: true},
		{name: "untracked unrelated rejected", status: "?? notes.txt\n", wantErr: true},
	}
	for _, tt := range cases {
		t.Run(tt.name, func(t *testing.T) {
			err := CheckDirtyStatus(tt.status, "api/api-contract.detected.yaml")
			if (err != nil) != tt.wantErr {
				t.Fatalf("error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestGenerateBranchNameAndValidation(t *testing.T) {
	now := time.Date(2026, 6, 8, 14, 35, 22, 0, time.UTC)
	got := GenerateBranchName(now)
	want := "gen-openapi/api-contract-drift-20260608-143522"
	if got != want {
		t.Fatalf("GenerateBranchName() = %q, want %q", got, want)
	}
	if !ValidBranchName(got) {
		t.Fatalf("expected generated branch to be valid")
	}
	for _, bad := range []string{"", "/bad", "bad/", "bad..name", "bad name", "bad~name"} {
		if ValidBranchName(bad) {
			t.Fatalf("expected invalid branch %q", bad)
		}
	}
}

func TestBodyIncludesReviewNotesAndFlags(t *testing.T) {
	report := diff.Report{Added: []diff.Change{{Key: diff.RouteKey{Method: "GET", Path: "/v1/new"}}}}
	body := Body(report, Options{Prune: true, IncludeInternal: true, SkipRender: true}, []string{"api/api-contract.yaml"})
	for _, want := range []string{
		"# API contract drift",
		"GET /v1/new",
		"Generated by `gen-openapi pr`",
		"will not be merged automatically",
		"`api/api-contract.yaml`",
		"--prune --include-internal --skip-render",
	} {
		if !strings.Contains(body, want) {
			t.Fatalf("body missing %q:\n%s", want, body)
		}
	}
}

func TestRun_NoDriftSkipsMutation(t *testing.T) {
	dir := setupRepoFiles(t, false)
	fr := &fakeRunner{outputs: map[string]string{
		"git rev-parse --show-toplevel":                   dir,
		"git status --porcelain=v1 --untracked-files=all": "",
	}, errors: map[string]error{}}
	res, err := Run(context.Background(), Options{
		ContractPath: filepath.Join(dir, "api/api-contract.yaml"),
		DetectedPath: filepath.Join(dir, "api/api-contract.detected.yaml"),
		DryRun:       true,
	}, fr)
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	if !res.NoDrift {
		t.Fatal("expected NoDrift")
	}
	if len(fr.calls) != 2 {
		t.Fatalf("expected only rev-parse and status calls, got %+v", fr.calls)
	}
}

func TestRun_DryRunNoMutation(t *testing.T) {
	dir := setupRepoFiles(t, true)
	fr := &fakeRunner{outputs: map[string]string{
		"git rev-parse --show-toplevel":                   dir,
		"git status --porcelain=v1 --untracked-files=all": "",
		"git branch --show-current":                       "main\n",
	}, errors: map[string]error{}}
	res, err := Run(context.Background(), Options{
		ContractPath:   filepath.Join(dir, "api/api-contract.yaml"),
		DetectedPath:   filepath.Join(dir, "api/api-contract.detected.yaml"),
		ApigConfigPath: filepath.Join(dir, "api/apig-config.yaml"),
		OpenAPIPath:    filepath.Join(dir, "api/openAPI.yaml"),
		DryRun:         true,
		Now:            time.Date(2026, 6, 8, 14, 35, 22, 0, time.UTC),
	}, fr)
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	if !res.DryRun || res.NoDrift {
		t.Fatalf("unexpected result: %+v", res)
	}
	if res.Branch != "gen-openapi/api-contract-drift-20260608-143522" {
		t.Fatalf("unexpected branch %q", res.Branch)
	}
	wantFiles := []string{filepath.Join(dir, "api/api-contract.yaml"), filepath.Join(dir, "api/openAPI.yaml")}
	if !reflect.DeepEqual(res.FilesUpdated, wantFiles) {
		t.Fatalf("unexpected files: %+v", res.FilesUpdated)
	}
	for _, c := range fr.calls {
		if c.Name == "gh" || (c.Name == "git" && len(c.Args) > 0 && c.Args[0] == "checkout") {
			t.Fatalf("dry-run should not call mutation command: %+v", c)
		}
	}
}

func TestRun_NormalModeGhArgs(t *testing.T) {
	dir := setupRepoFiles(t, true)
	fr := &fakeRunner{outputs: map[string]string{
		"git rev-parse --show-toplevel":                   dir,
		"git status --porcelain=v1 --untracked-files=all": "",
		"git diff --cached --quiet":                       "",
		"gh pr create --base main --head test/branch --title My PR --body-file - --draft --label x --label y": "https://example/pr/1\n",
	}, errors: map[string]error{
		"git diff --cached --quiet": fmt.Errorf("exit status 1"),
	}}
	res, err := Run(context.Background(), Options{
		ContractPath:   filepath.Join(dir, "api/api-contract.yaml"),
		DetectedPath:   filepath.Join(dir, "api/api-contract.detected.yaml"),
		ApigConfigPath: filepath.Join(dir, "api/apig-config.yaml"),
		OpenAPIPath:    filepath.Join(dir, "api/openAPI.yaml"),
		Base:           "main",
		Branch:         "test/branch",
		Title:          "My PR",
		Labels:         []string{"x", "y"},
		Draft:          true,
	}, fr)
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	if res.PROutput != "https://example/pr/1" {
		t.Fatalf("unexpected PR output: %q", res.PROutput)
	}
	last := fr.calls[len(fr.calls)-1]
	if last.Name != "gh" {
		t.Fatalf("expected last command gh, got %+v", last)
	}
	if !strings.Contains(last.Stdin, "will not be merged automatically") {
		t.Fatal("expected PR body on stdin")
	}
}

func setupRepoFiles(t *testing.T, withDrift bool) string {
	t.Helper()
	dir := t.TempDir()
	apiDir := filepath.Join(dir, "api")
	if err := os.MkdirAll(apiDir, 0o755); err != nil {
		t.Fatal(err)
	}
	canonical := mkContract(route("GET", "/v1/existing"))
	detectedRoutes := []contract.Route{route("GET", "/v1/existing")}
	if withDrift {
		detectedRoutes = append(detectedRoutes, route("POST", "/v1/new"))
	}
	detected := mkContract(detectedRoutes...)
	if err := output.WriteYAML(filepath.Join(apiDir, "api-contract.yaml"), canonical); err != nil {
		t.Fatal(err)
	}
	if err := output.WriteYAML(filepath.Join(apiDir, "api-contract.detected.yaml"), detected); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(apiDir, "apig-config.yaml"), []byte(`apiVersion: infra.example.com/v1
kind: HuaweiApigConfig
metadata:
  name: test-apig
spec:
  gatewayUrl: https://example.com
  backend:
    type: HTTP
    scheme: https
    address: backend.example.com
    timeout: 5000
    retryCount: "0"
  defaults:
    matchMode: NORMAL
    requestType: public
  securitySchemes: {}
`), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

func mkContract(routes ...contract.Route) *contract.ApiContract {
	return &contract.ApiContract{
		APIVersion: "infra.example.com/v1",
		Kind:       "ApiContract",
		Metadata:   contract.Metadata{Name: "test", Title: "Test", Version: "1.0.0"},
		Spec:       contract.Spec{BasePath: "/api", Routes: routes, Schemas: map[string]*contract.Schema{}},
	}
}

func route(method, path string) contract.Route {
	return contract.Route{OperationID: method + strings.ReplaceAll(path, "/", "_"), Method: method, Path: path, Auth: "none"}
}
